In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 1. Load the CSV Dataset

In [ ]:
import pandas as pd

file_path = '/content/drive/MyDrive/sem3/mini project - Bipolar Disorder/bipolar-raw-dataset.csv'
df = pd.read_csv(file_path)

display(df.head())

,Record ID,Gender:,Marital Status:,No of biological children:,Date of Assessment of File/ Interview:,Date of Registration:,Date of Birth:,Age,Birth City:,Birth State,...,Criteria B Score,Total Score,Kindly rate your social life and friendships before becoming ill,Kindly rate your self-Care and activities of daily living over the last 5 years,"In the last 5 years, were you going to-",Kindly rate your occupational functioning in the last 5 years.,Are you currently married or in a long-term relationship?,Kindly rate any impairment in capacity for intimate relationship in the last five years,"Any additional information pertaining to self care, work and social adjustment-",Genotyped?
0,2,Male,Married,2.0,2025-12-22,1996-01-17,1976-01-01,50.0,Kanakapura,Karnataka,...,2.0,7.0,3.0,1.0,Worked outside home,1.0,Yes,1.0,NaN,Yes
1,3,Male,Married,0.0,2023-02-07,1995-04-04,1956-01-01,67.1,BANGALORE,KARNATAKA,...,1.0,9.0,NaN,2.0,NaN,2.0,No,1.0,NaN,Yes
2,4,Male,Married,NaN,2023-02-13,1995-04-27,1975-01-01,48.1,NAMAKKAL,TAMIN NADU,...,0.0,10.0,NaN,4.0,Worked outside home,4.0,Yes,3.0,NaN,Yes
3,5,Male,Married,NaN,2023-02-14,1995-03-22,1965-01-01,58.1,MYSORE,KARNATAKA,...,2.0,8.0,NaN,4.0,NaN,NaN,Yes,3.0,NaN,Yes
4,6,Female,Married,1.0,2023-02-15,1995-04-07,1974-01-01,49.1,BANGALORE,KARNATAKA,...,4.0,6.0,3.0,5.0,NaN,4.0,Yes,3.0,NaN,Yes

## 2. Clean dataset column names

remove special characters like '(', ':', '=' etc...

transform " "(space) into underscores

In [ ]:
import re

def clean_column_names(dataframe: pd.DataFrame)-> pd.DataFrame:
  '''
  This function takes dataframe as input and return the dataframe with cleaned column names
  '''
  cleaned_cols = []
  for col in df.columns:
    c = col.strip().lower()
    c = re.sub(r'[^\w\s]', '', c)
    c = re.sub(r'\s+', '_', c)
    cleaned_cols.append(c)
  dataframe.columns = cleaned_cols # replacing the actual dataframe column names with new cleaned column names
  return dataframe

#call the function
df = clean_column_names(df)

print("Cleaned column count = ", len(df.columns))
print(df.columns.tolist())

Cleaned column count =  430
['record_id', 'gender', 'marital_status', 'no_of_biological_children', 'date_of_assessment_of_file_interview', 'date_of_registration', 'date_of_birth', 'age', 'birth_city', 'birth_state', 'birth_country', 'current_city', 'current_state', 'current_country', 'background', 'religion', 'income', 'education', 'years_of_education', 'occupation', 'occupation_details', 'detailed_workup', 'full_diagnosis', 'family_history_of_psychiatric_illness_in_first_degree_relatives_choice1_schizophreniapsychosis', 'family_history_of_psychiatric_illness_in_first_degree_relatives_choice2_bpad', 'family_history_of_psychiatric_illness_in_first_degree_relatives_choice3_rdd', 'family_history_of_psychiatric_illness_in_first_degree_relatives_choice4_substance_dependence', 'family_history_of_psychiatric_illness_in_first_degree_relatives_choice5_anxiety_disorders', 'fdr_scz_count', 'fdr_bpad_count', 'fdr_rdd_count', 'fdr_sud_count', 'fdr_anx_count', 'total_number_of_affected_first_degree_relatives', 'family_history_of_psychiatric_illness_in_second_degree_relatives_choice1_schizophreniapsychosis', 'family_history_of_psychiatric_illness_in_second_degree_relatives_choice2_bpad', 'family_history_of_psychiatric_illness_in_second_degree_relatives_choice3_rdd', 'family_history_of_psychiatric_illness_in_second_degree_relatives_choice4_substance_dependence', 'family_history_of_psychiatric_illness_in_second_degree_relatives_choice5_anxiety_disorders', 'sdr_scz_count', 'sdr_bpad_count', 'sdr_rdd_count', 'sdr_sud_count', 'sdr_anx_count', 'total_number_of_affected_second_degree_relatives', 'are_your_parents_related_kindly_choose_the_parentage', 'what_was_your_birth_weight', 'were_you_born_', 'did_your_mother_have_any_health_issues_while_she_was_pregnant_with_you', 'if_yes_please_provide_the_details_of_the_health_condition', 'has_the_patient_appeared_backward_slow_dull_or_very_less_intelligent_in_everything_from_childhood', 'has_the_patient_always_had_difficulty_in_learning_to_do_things_like_individuals_of_his_age', 'if_reviewing_the_file_is_there_any_documentation_of_intellectual_disability', 'does_the_patient_remain_solitary_and_selfabsorbed_most_of_the_time_with_no_interest_in_people_from_early_childhood', 'from_early_childhood_does_the_patient_not_respond_to_name_calling_or_doesnt_respond_when_spoken_to_most_of_the_time_though_heshe_can_hear_other_sounds', 'does_the_patient_keep_on_repeating_the_same_action_or_activity_such_as_body_rocking_shaking_hands_in_front_of_eyes_or_repeatedly_making_the_same_meaningless_sounds_from_early_childhood', 'if_reviewing_the_file_is_there_any_documentation_of_autism', 'if_reviewing_the_file_is_there_any_documentation_of_adhd', 'if_reviewing_the_file_is_there_any_documentation_of_odd_or_conduct_disorder', 'has_the_patient_ever_been_diagnosed_with_a_psychiatric_illness_caused_by_head_injury_brain_lesions_seizures_central_nervous_system_infections_or_other_neurological_illness', 'if_yes_kindly_provide_details', 'first_episode', 'date_of_onset_of_illness_first_episode', 'type_of_onset_of_first_episode', 'age_at_onset_of_illness_first_episode', 'index_episode_episode_at_presentation_to_nimhans', 'date_of_onset_of_index_episode', 'age_at_onset_of_index_episode', 'type_of_onset_of_index_episode', 'postpartum_onset', 'time_of_postpartum_onset', 'episode_sequence', 'total_number_of_episodes', 'lifetime_history_of_rapid_cycling', 'interepisodic_remission', 'if_partial_remission_then_persistent', 'maximum_interepisodic_duration_in_months', 'total_duration_of_illness_in_months', 'total_duration_of_all_episodes_in_months', 'percentage_of_time_with_symptoms', 'number_of_ip_care_recieved', 'comorbid_choicenone', 'comorbid_choicenicotine_dependence', 'comorbid_choicealcohol_dependence', 'comorbid_choicecannabis_dependence', 'comorbid_choiceanxiety_disorder', 'comorbid_choicehypothyroid_disorder', 'comorbid_choiceocd', 'comorbid_choiceother', 'if_other_specify_details', 'psychiatric_comorbidity_choiceanxiety_disorders', 'psychiatric_comorbidity_choicepersonality_disorders', 'psychiatric_comorbidity_choiceocrds', 'psychiatric_comorbidity_choicetrauma_and_related_disorders', 'psychiatric_comorbidity_choiceadhd', 'psychiatric_comorbidity_choiceeating_disorders', 'psychiatric_comorbidity_choicesomatoform_and_pain_related_disorders', 'psychiatric_comorbidity_choiceother', 'psychiatric_comorbidity_choicenone', 'psychiatric_comorbidity_choicenot_available', 'other_psychiatric_comorbidity', 'medical_comorbidity_choicediabetes_mellitus', 'medical_comorbidity_choicesystemic_hypertension', 'medical_comorbidity_choiceischemic_heart_disease', 'medical_comorbidity_choicedyslipidemia', 'medical_comorbidity_choicehypothyroidism', 'medical_comorbidity_choicemigraine', 'medical_comorbidity_choiceseizure_disorder', 'medical_comorbidity_choiceother', 'medical_comorbidity_choicenone', 'medical_comorbidity_choicenot_available', 'other_medical_comorbidity', 'comorbid_substance_use_disorder_choicetobacco_dependence', 'comorbid_substance_use_disorder_choicealcohol_dependence', 'comorbid_substance_use_disorder_choicecannabis_dependence', 'comorbid_substance_use_disorder_choicealcohol_harmful_use', 'comorbid_substance_use_disorder_choicecannabis_harmful_use', 'comorbid_substance_use_disorder_choiceother', 'comorbid_substance_use_disorder_choicenone', 'comorbid_substance_use_disorder_choicenot_available', 'other_comorbid_substance_use_disorder', 'has_there_ever_been_a_manic_episode', 'total_number_of_hypomanic_episodes', 'total_number_of_manic_episodes', 'total_number_of_mixed_episodes', 'when_was_the_onset_of_first_manic_episode', 'age_at_onset_of_first_manic_episode', 'total_duration_of_hypomanic_episodes_in_months', 'total_duration_of_manic_episodes_in_months', 'total_duration_of_mixed_episodes_in_months', 'when_was_onset_the_most_severe_episode_or_the_most_recent_episode_whichever_the_patient_can_recollect_better', 'precipitating_factors_choicepoor_compliance', 'precipitating_factors_choicestressors', 'precipitating_factors_choiceuse_of_alcoholdrugs', 'precipitating_factors_choiceantidepressants', 'precipitating_factors_choiceany_other_medical_condition', 'precipitating_factors_choicepregnancy', 'precipitating_factors_choicenone', 'specify_medical_condition', 'duration_of_the_episode', 'persistent_elevated_mood', 'persistent_irritability', 'dec_need_for_sleep', 'inc_speech_rate_and_amount', 'foiracing_thoughts', 'distractibility', 'inc_pma', 'grandiosity', 'overfamiliarity', 'increased_sexual_interest', 'agitation', 'high_risk_behaviours', 'insight', 'social_dysfunction', 'relationship_dysfunction', 'occupational_dysfunction', 'hospitalized', 'psychotic_symptoms', 'has_there_ever_been_a_depressive_episode', 'when_was_the_onset_of_first_depressive_episode', 'age_at_onset_of_first_depressive_episode', 'total_number_of_depressive_episodes', 'total_duration_of_depressive_episodes_in_months', 'when_was_the_most_severe_episode_or_the_most_recent_episode_whichever_the_patient_can_recollect_better', 'precipitating_factors_choicepoor_compliance1', 'precipitating_factors_choicestressors1', 'precipitating_factors_choiceuse_of_alcoholdrugs1', 'precipitating_factors_choicepregnancy1', 'precipitating_factors_choiceany_other_medical_condition1', 'precipitating_factors_choicenone1', 'spec_med_con', 'duration_of_the_episode1', 'per_low_mood', 'emptiness', 'anh', 'weight', 'appetite', 'sleep', 'pma', 'ef', 'guilt', 'worthless', 'poor_conc', 'self_harm_ideation', 'fear_of_dying', 'suicidal_attempt', 'rel_dysfunc', 'occ_dys', 'sosh_dys', 'insight1', 'hosp', 'psy_symp', 'has_there_ever_been_psychotic_symptoms', 'when_did_the_first_psychotic_symptoms_appear', 'age_when_the_first_psychotic_symptoms_appeared', 'if_psychotic_symptoms_present_were_they', 'del_ref', 'del_per', 'del_gran', 'del_sin', 'del_infidel', 'del_ctrl', 'del_soma', 'thought_phen', 'ah', 'vh', 'disorg_speech', 'disorg_behaviour', 'catatonia', 'avolition', 'avolition_occurred_mostly_during_choiceeuthymia', 'avolition_occurred_mostly_during_choicemania', 'avolition_occurred_mostly_during_choicedepression', 'avolition_occurred_mostly_during_choicena', 'blunted_affect', 'diminished_emotional_expressiveness_occurred_mostly_during_choiceeuthymia', 'diminished_emotional_expressiveness_occurred_mostly_during_choicemania', 'diminished_emotional_expressiveness_occurred_mostly_during_choicedepression', 'diminished_emotional_expressiveness_occurred_mostly_during_choicena', 'rate_negative_symptoms', 'sui_idea', 'sui_att', 'att_num', 'polarity_attempt_choicemania', 'polarity_attempt_choicedepression', 'polarity_attempt_choicemixed', 'stressors_leading_to_suicide_attempt', 'details_of_stressor', 'mode', 'intention', 'leth', 'termination', 'hospitalization', 'in_first_five_years_of_illness_after_onset_rate_the_amount_of_time_spent_primarily_in_manic_vs_depressive_symptoms_on_5point_scale', 'in_more_recent_years_of_illness_rate_the_amount_of_time_spent_primarily_in_manic_vs_depressive_symptoms_on_5point_scale', 'use_of_antidepressants', 'effect_of_antidepressant', 'worsening_of_mood_stability_or_mania_due_to_antidepressants', 'rate_prominence_of_mixed_episodes', 'rate_time_spent_euthymic_since_onset', 'severity_of_illness_as_time_has_gone_onna_if_illness_is_5_years', 'interepisodic_recovery', 'anxietypanic_symptoms', 'insightinterepisode', 'date1', 'date2', 'date3', 'date4', 'date5', 'date6', 'date7', 'date8', 'date9', 'date10', 'date11', 'date12', 'date13', 'date14', 'date15', 'date16', 'date17', 'date18', 'date19', 'date20', 'date21', 'date22', 'date23', 'date24', 'date25', 'creat1', 'creat2', 'creat3', 'creat4', 'creat5', 'creat6', 'creat7', 'creat8', 'creat9', 'creat10', 'creat11', 'creat12', 'creat13', 'creat14', 'creat15', 'creat16', 'creat17', 'creat18', 'creat19', 'creat21', 'creat20', 'creat22', 'creat23', 'creat24', 'creat25', 't3_1', 't3_2', 't3_3', 't3_4', 't3_5', 't3_6', 't3_7', 't3_8', 't3_9', 't3_10', 't3_11', 't3_12', 't3_13', 't3_14', 't3_15', 't3_16', 't3_17', 't3_18', 't3_19', 't3_20', 't3_21', 't3_22', 't3_23', 't3_24', 't3_25', 't4_1', 't4_2', 't4_3', 't4_4', 't4_5', 't4_6', 't4_7', 't4_8', 't4_9', 't4_10', 't4_11', 't4_12', 't4_13', 't4_14', 't4_15', 't4_16', 't4_17', 't4_18', 't4_19', 't4_20', 't4_21', 't4_22', 't4_23', 't4_24', 't4_25', 'tsh1', 'tsh2', 'tsh3', 'tsh4', 'tsh5', 'tsh6', 'tsh7', 'tsh8', 'tsh9', 'tsh10', 'tsh11', 'tsh12', 'tsh13', 'tsh14', 'tsh15', 'tsh16', 'tsh17', 'tsh18', 'tsh19', 'tsh20', 'tsh21', 'tsh22', 'tsh23', 'tsh24', 'tsh25', 'li1', 'li2', 'li3', 'li4', 'li5', 'li6', 'li7', 'li8', 'li9', 'li10', 'li11', 'li12', 'li13', 'li14', 'li15', 'li16', 'li17', 'li18', 'li19', 'li20', 'li21', 'li22', 'li23', 'li24', 'li25', 'ever_been_treated_with_lithium', 'rate_response_to_lithium_treatment', 'ever_been_treated_with_anticonvulsants', '1_anticonvulsant', 'response', '2_anticonvulsant', 'response1', 'ever_been_treated_with_antipsychotics', 'antipsychotic', 'response2', 'antipsychotic1', 'response3', 'ect_recieved', 'number_of_depressive_episodes_requiring_ect', 'number_of_ects_for_depressive_episode', 'number_of_manic_episodes_requiring_ects', 'number_of_ects_for_manic_episodes', 'number_of_mixed_episodes_requiring_ects', 'number_of_ects_for_mixed_episodes', 'criterion_a', 'b1', 'b2', 'b3', 'b4', 'b5', 'a_criterion_score', 'criteria_b_score', 'total_score', 'kindly_rate_your_social_life_and_friendships_before_becoming_ill', 'kindly_rate_your_selfcare_and_activities_of_daily_living_over_the_last_5_years', 'in_the_last_5_years_were_you_going_to', 'kindly_rate_your_occupational_functioning_in_the_last_5_years', 'are_you_currently_married_or_in_a_longterm_relationship', 'kindly_rate_any_impairment_in_capacity_for_intimate_relationship_in_the_last_five_years', 'any_additional_information_pertaining_to_self_care_work_and_social_adjustment', 'genotyped']

## 3. Feature extraction

extracting core features from the 430 available features in the raw dataset

In [ ]:
selected_features = [
    # Demographics & Context
    'age', 'gender', 'marital_status', 'education',

    # Trajectory & Episode Metrics
    'age_at_onset_of_illness_first_episode',
    'total_number_of_episodes',
    'total_duration_of_illness_in_months',
    'total_duration_of_all_episodes_in_months',
    'total_duration_of_hypomanic_episodes_in_months',
    'total_number_of_manic_episodes',
    'total_number_of_hypomanic_episodes',
    'total_number_of_mixed_episodes',
    'total_number_of_depressive_episodes',
    'lifetime_history_of_rapid_cycling',
    'percentage_of_time_with_symptoms',
    'interepisodic_remission',
    'maximum_interepisodic_duration_in_months',
    'rate_time_spent_euthymic_since_onset',
    'rate_prominence_of_mixed_episodes',
    'in_first_five_years_of_illness_after_onset_rate_the_amount_of_time_spent_primarily_in_manic_vs_depressive_symptoms_on_5point_scale',
    'in_more_recent_years_of_illness_rate_the_amount_of_time_spent_primarily_in_manic_vs_depressive_symptoms_on_5point_scale',

    # Manic Symptom Domain
    'has_there_ever_been_a_manic_episode',
    'persistent_elevated_mood', 'persistent_irritability', 'dec_need_for_sleep',
    'inc_speech_rate_and_amount', 'foiracing_thoughts', 'distractibility',
    'inc_pma', 'grandiosity', 'overfamiliarity', 'increased_sexual_interest',
    'agitation', 'high_risk_behaviours',

    # Depressive Symptom Domain
    'has_there_ever_been_a_depressive_episode',
    'per_low_mood', 'emptiness', 'anh', 'ef', 'guilt', 'worthless',
    'poor_conc', 'self_harm_ideation', 'suicidal_attempt',

    # Psychotic & Negative Symptom Domain
    'has_there_ever_been_psychotic_symptoms', 'psy_symp',
    'del_ref', 'del_per', 'del_gran', 'del_sin', 'del_ctrl', 'del_soma',
    'thought_phen', 'ah', 'vh', 'disorg_speech', 'disorg_behaviour',
    'catatonia', 'avolition', 'blunted_affect', 'rate_negative_symptoms',

    # Severity & Functioning
    'insightinterepisode', 'social_dysfunction', 'relationship_dysfunction',
    'occupational_dysfunction', 'kindly_rate_your_occupational_functioning_in_the_last_5_years',
    'hospitalized', 'number_of_ip_care_recieved', 'a_criterion_score', 'criteria_b_score', 'total_score',

    # Comorbidities
    'psychiatric_comorbidity_choiceanxiety_disorders',
    'psychiatric_comorbidity_choicepersonality_disorders',
    'psychiatric_comorbidity_choiceocrds',
    'psychiatric_comorbidity_choicetrauma_and_related_disorders',
    'psychiatric_comorbidity_choiceadhd',
    'psychiatric_comorbidity_choiceeating_disorders',
    'comorbid_substance_use_disorder_choicetobacco_dependence',
    'comorbid_substance_use_disorder_choicealcohol_dependence',
    'comorbid_substance_use_disorder_choicecannabis_dependence'
]

df_subset = df[selected_features].copy()
print("Actual columns length in selected features list: ", len(selected_features))
print("Selected Subset Shape: ", df_subset.shape)

Actual columns length in selected features list:  80
Selected Subset Shape:  (367, 80)

In [ ]:
rename_dict = {
    'age_at_onset_of_illness_first_episode': 'age_onset',
    'has_there_ever_been_a_manic_episode': 'ever_manic',
    'has_there_ever_been_a_depressive_episode': 'ever_depressive',
    'has_there_ever_been_psychotic_symptoms': 'ever_psychotic',
    'foiracing_thoughts': 'racing_thoughts',
    'inc_pma': 'pma_mania',
    'per_low_mood': 'low_mood',
    'anh': 'anhedonia',
    'ef': 'executive_dysfunction',
    'poor_conc': 'poor_concentration',
    'kindly_rate_your_occupational_functioning_in_the_last_5_years': 'occupational_func_5yr',
    'in_first_five_years_of_illness_after_onset_rate_the_amount_of_time_spent_primarily_in_manic_vs_depressive_symptoms_on_5point_scale': 'mania_vs_dep_first5yr',
    'in_more_recent_years_of_illness_rate_the_amount_of_time_spent_primarily_in_manic_vs_depressive_symptoms_on_5point_scale': 'mania_vs_dep_recent',
    'psychiatric_comorbidity_choiceanxiety_disorders': 'comorbid_anxiety',
    'psychiatric_comorbidity_choicepersonality_disorders': 'comorbid_personality',
    'psychiatric_comorbidity_choiceocrds': 'comorbid_ocd',
    'psychiatric_comorbidity_choicetrauma_and_related_disorders': 'comorbid_trauma',
    'psychiatric_comorbidity_choiceadhd': 'comorbid_adhd',
    'psychiatric_comorbidity_choiceeating_disorders': 'comorbid_eating',
    'comorbid_substance_use_disorder_choicetobacco_dependence': 'substance_tobacco',
    'comorbid_substance_use_disorder_choicealcohol_dependence': 'substance_alcohol',
    'comorbid_substance_use_disorder_choicecannabis_dependence': 'substance_cannabis'
}

df_subset = df_subset.rename(columns=rename_dict)
df_subset.head()

,age,gender,marital_status,education,age_onset,total_number_of_episodes,total_duration_of_illness_in_months,total_duration_of_all_episodes_in_months,total_duration_of_hypomanic_episodes_in_months,total_number_of_manic_episodes,...,total_score,comorbid_anxiety,comorbid_personality,comorbid_ocd,comorbid_trauma,comorbid_adhd,comorbid_eating,substance_tobacco,substance_alcohol,substance_cannabis
0,50.0,Male,Married,8th std,17.0,11.0,395.6,41.5,2,7.0,...,7.0,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Checked,Unchecked,Unchecked
1,67.1,Male,Married,NaN,38.6,6.0,342.2,13.0,0,4.0,...,9.0,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked
2,48.1,Male,Married,"MSC, B.ED",20.3,7.0,333.6,7.0,0,6.0,...,10.0,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked
3,58.1,Male,Married,NOT LITERATE,30.2,6.0,334.7,7.0,0,4.0,...,8.0,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked
4,49.1,Female,Married,NaN,21.2,11.0,335.2,16.0,0,9.0,...,6.0,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked,Unchecked

## 4. Data cleaning

- analyse values of each feature
- handle missing values

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

missing_count = df_subset.isnull().sum()
# print(missing_count.to_dict())

missing_percent = (missing_count/len(df_subset))*100
# print(missing_percent)

dictionary = dict(missing_percent)
below20 = [key for key,value in dictionary.items() if value < 20]
btw20and40 = [key for key,value in dictionary.items() if value >= 20 and value < 40]
above40 = [key for key,value in dictionary.items() if value >= 40]

print(f"Missing Count below 20% {below20} \n Misssing count = {len(below20)}")
print(f"Missing Count between 20% and 40% {btw20and40} \n Misssing count = {len(btw20and40)}")
print(f"Missing Count above 40% {above40} \n Misssing count = {len(above40)}")

Missing Count below 20% ['age', 'gender', 'marital_status', 'total_number_of_episodes', 'total_duration_of_all_episodes_in_months', 'total_number_of_manic_episodes', 'lifetime_history_of_rapid_cycling', 'rate_time_spent_euthymic_since_onset', 'rate_prominence_of_mixed_episodes', 'mania_vs_dep_first5yr', 'mania_vs_dep_recent', 'persistent_elevated_mood', 'persistent_irritability', 'dec_need_for_sleep', 'inc_speech_rate_and_amount', 'racing_thoughts', 'distractibility', 'pma_mania', 'grandiosity', 'overfamiliarity', 'increased_sexual_interest', 'agitation', 'social_dysfunction', 'relationship_dysfunction', 'occupational_dysfunction', 'hospitalized', 'comorbid_anxiety', 'comorbid_personality', 'comorbid_ocd', 'comorbid_trauma', 'comorbid_adhd', 'comorbid_eating', 'substance_tobacco', 'substance_alcohol', 'substance_cannabis']
 Misssing count = 35
Missing Count between 20% and 40% ['education', 'age_onset', 'total_duration_of_illness_in_months', 'total_duration_of_hypomanic_episodes_in_months', 'total_number_of_hypomanic_episodes', 'total_number_of_mixed_episodes', 'total_number_of_depressive_episodes', 'percentage_of_time_with_symptoms', 'interepisodic_remission', 'maximum_interepisodic_duration_in_months', 'ever_manic', 'high_risk_behaviours', 'ever_depressive', 'ever_psychotic', 'avolition', 'blunted_affect', 'rate_negative_symptoms', 'insightinterepisode', 'occupational_func_5yr', 'number_of_ip_care_recieved', 'a_criterion_score', 'criteria_b_score', 'total_score']
 Misssing count = 23
Missing Count above 40% ['low_mood', 'emptiness', 'anhedonia', 'executive_dysfunction', 'guilt', 'worthless', 'poor_concentration', 'self_harm_ideation', 'suicidal_attempt', 'psy_symp', 'del_ref', 'del_per', 'del_gran', 'del_sin', 'del_ctrl', 'del_soma', 'thought_phen', 'ah', 'vh', 'disorg_speech', 'disorg_behaviour', 'catatonia']
 Misssing count = 22

In [ ]:
numerical_cols = df_subset.select_dtypes(include=['int64', 'float64']).columns.to_list()
print(len(numerical_cols))
categorical_cols = df_subset.select_dtypes(include=['object', 'category']).columns.to_list()
print(len(categorical_cols))

21
59

In [ ]:
uniqsetofvaluesCat = {}
for col in categorical_cols:
  uniqsetofvaluesCat[col] = set(df_subset[col].to_list())
  print(f"{col} : {set(df_subset[col].to_list())}")

gender : {'Female', 'Male', nan}
marital_status : {'Separated', 'Married', 'Re-married', nan, 'Divorced', 'Not available', 'Widowed', 'Never married'}
education : {'ITI', '10th', '12th', '10th std', 'II nd PUC', '3rd std.', 'secondary', '7th Standard', '7th standard', 'Graduate', 'Primary ', '4th std', 'Bcom', '10TH STD', 'Ist PUC', 'II nd standard', 'Diploma In civil engineering', 'diploma student', '10 th class ', '5th class', 'BCom', '10th standard', 'diploma', '3rd Standard', '3', '8', 'Diploma in CS', 'NOT LITERATE', 'illiterate ', 'High school', 'Graduation', 'graduate ', 'BE', 'SSLC', '1st PUC', 'B.E.', '8th std', 'BA, DED, CET', 'Illiterate ', 'Diploma in software engineering', '5th Standard', '9th standard', '8th class ', '6th standard', 'Illiterate', 'SSLC fail', '9', 'puc', '4 th standard', 'Sslc', 'BA Sanskrit ', 'B.Com', '9th Standard', '5th standard', '9th std', '3RD STD', '2nd standard', '5 standard', 'Diploma Metallurgy engineering', '7th', 'Upto 7th Standard', '5th', '12', 'PUC', 'Secondary', 'no formal education', 'II nd year degree', 'high school', 'SECONDARY ', '8 th class', 'ITI course', '2', 'Primary', 'PRIMARY', 'Student ', '3rd', '4th Standard', '6th grade ', '3rd standard', 'TCH ', 'Puc', '9th', 'SSLC ', '8th std.', '4th standard', 'Graduate - BA', '11 th ', 'GRADUATE', nan, '10th pass', 'II PUC', 'MA', '5', 'Primary School', 'PVC II', 'II Standard', '8th ', '8th', '8th standard', '6th class', 'Illeterate', '10th Standard', '9th complete ', 'B.A', '12th std', 'PUC 1ST', '6TH STD', '7 standard', 'illiterate', '12th Standard', '10', 'PUC SECOND ', '5th std', 'illeterate', '5th ', '11th', 'b.com', 'IInd year degree', 'MSC, B.ED', '997', '2nd ', '8th Standard', 'BeD', 'BTech ', '7TH STD', 'BA', '7th std', '7', 'BBM 2nd year', '6th std', 'bcom drop out', 'Diploma', '11TH STD', '4', 'Graduate ', 'BA 1st year '}
total_duration_of_hypomanic_episodes_in_months : {'11', nan, '18', '0', '0.25', '1-11-2002', '4', '1.5', '1', '2', '0.5', '6', '3'}
lifetime_history_of_rapid_cycling : {'No', nan, 'Yes'}
interepisodic_remission : {'Complete', nan, 'No remission', 'Partial'}
ever_manic : {'No', nan, 'Yes'}
persistent_elevated_mood : {'No', nan, 'Yes'}
persistent_irritability : {'No', nan, 'Yes'}
dec_need_for_sleep : {'No', nan, 'Yes'}
inc_speech_rate_and_amount : {'No', nan, 'Yes'}
racing_thoughts : {'No', nan, 'Yes'}
distractibility : {'No', nan, 'Yes'}
pma_mania : {'No', nan, 'Yes'}
grandiosity : {'No', nan, 'Yes'}
overfamiliarity : {'No', nan, 'Yes'}
increased_sexual_interest : {'No', nan, 'Yes'}
agitation : {'No', nan, 'Yes'}
high_risk_behaviours : {'No', nan, 'Yes'}
ever_depressive : {'No', nan, 'Yes'}
low_mood : {'No', nan, 'Yes'}
emptiness : {'No', nan, 'Yes'}
anhedonia : {'No', nan, 'Yes'}
executive_dysfunction : {'No', nan, 'Yes'}
guilt : {'No', nan, 'Yes'}
worthless : {'No', nan, 'Yes'}
poor_concentration : {'No', nan, 'Yes'}
self_harm_ideation : {'No', nan, 'Yes'}
suicidal_attempt : {'No', nan, 'Yes'}
ever_psychotic : {'No', nan, 'Yes'}
psy_symp : {'No', nan, 'Yes'}
del_ref : {'No', nan, 'Yes'}
del_per : {'No', nan, 'Yes'}
del_gran : {'No', nan, 'Yes'}
del_sin : {'No', nan, 'Yes'}
del_ctrl : {'No', nan, 'Yes'}
del_soma : {'No', nan, 'Yes'}
thought_phen : {'No', nan, 'Yes'}
ah : {'No', nan, 'Yes'}
vh : {'No', nan, 'Yes'}
disorg_speech : {'No', nan, 'Yes'}
disorg_behaviour : {'No', nan, 'Yes'}
catatonia : {'No', nan, 'Yes'}
avolition : {'No', nan, 'Yes'}
blunted_affect : {'No', nan, 'Yes'}
rate_negative_symptoms : {'Equivocal', 'Present- Severe', nan, 'Present- Mild', 'Present- Moderate', 'Not present'}
social_dysfunction : {'No', nan, 'Yes'}
relationship_dysfunction : {'No', nan, 'Yes'}
occupational_dysfunction : {'No', nan, 'Yes'}
hospitalized : {'No', nan, 'Yes'}
comorbid_anxiety : {'Unchecked', 'Checked'}
comorbid_personality : {'Unchecked', 'Checked'}
comorbid_ocd : {'Unchecked'}
comorbid_trauma : {'Unchecked'}
comorbid_adhd : {'Unchecked'}
comorbid_eating : {'Unchecked'}
substance_tobacco : {'Unchecked', 'Checked'}
substance_alcohol : {'Unchecked', 'Checked'}
substance_cannabis : {'Unchecked', 'Checked'}

In [ ]:
for col in categorical_cols:
  df_subset[col] = df_subset[col].fillna("Unknown")

In [ ]:
uniqsetofvaluesNum = {}
for col in numerical_cols:
  uniqsetofvaluesNum[col] = set(df_subset[col].to_list())
  print(f"{col} : {set(df_subset[col].to_list())}")

age : {nan, nan, 11.2, 15.2, 17.7, 18.6, 19.4, 20.9, 21.1, 22.0, 23.7, 24.2, 21.8, 26.5, 24.0, 28.7, 28.2, 30.7, 30.4, 32.5, 33.7, 34.4, 35.2, 36.7, 36.2, 37.1, 38.2, 39.2, 39.1, 41.2, 42.2, 43.2, 44.3, 45.2, 46.1, 47.1, 48.1, 49.1, 51.3, 50.0, 53.3, 54.5, 54.6, 55.7, 55.2, 55.3, 56.7, 57.7, 52.1, 55.1, 58.2, 58.1, 59.1, 61.1, 59.2, 59.6, 67.1, 62.9, 69.5, 67.5, 69.3, 74.2, 75.3, 76.1, 74.8, 75.0, 72.3, nan, nan, 74.5, 74.7, 84.0, 83.1, 17.4, nan, nan, 40.3, 19.0, nan, nan, nan, 21.4, 21.5, nan, nan, 21.0, 22.9, nan, 23.1, 23.5, 23.0, nan, 25.0, 25.1, 27.5, 46.0, 27.4, 46.5, 27.0, 28.6, 28.9, nan, 29.1, 29.9, 30.0, nan, nan, 30.9, 31.1, 31.6, nan, 31.0, 32.9, 32.1, 33.9, 33.6, nan, 39.6, 34.3, 34.9, nan, 34.8, 34.2, 35.9, 35.5, nan, 35.0, 35.3, 36.9, 36.1, 36.6, nan, 37.7, 37.2, 37.5, 37.4, 37.6, 38.0, 38.6, 38.1, 38.9, 38.8, 39.3, 39.8, nan, 39.0, nan, 40.7, 40.1, 40.4, 40.6, nan, 41.6, 41.7, 41.3, 40.9, 41.0, 42.6, 42.4, 42.9, 42.8, 42.0, 43.7, 43.1, 43.4, nan, 42.1, 44.6, 44.0, 44.8, 44.1, nan, 45.6, 45.1, 45.7, 45.0, 46.2, 46.9, 46.4, 46.8, 46.7, 46.3, 47.2, 47.4, 47.7, 47.9, 48.3, 48.6, 48.5, nan, 49.7, 49.6, 49.4, nan, 49.9, 50.2, 50.8, 50.1, 50.3, 50.6, 51.2, 51.8, 51.1, 51.9, 51.0, 52.2, 52.4, 52.5, 52.8, 52.3, 53.2, 53.7, 53.5, 53.8, 53.6, 54.9, 54.1, 53.1, 54.0, nan, 56.2, 56.9, 56.1, nan, 57.2, 52.0, 57.9, 58.6, 59.7, nan, 60.0, 60.8, 60.6, 61.3, 61.0, 61.8, nan, 62.0, 62.7, 53.0, 63.3, nan, nan, 64.1, 64.3, 65.8, nan, 66.2, nan, 66.9, nan, nan, 67.2, nan, 17.3, 68.9, nan, nan, 69.0, nan, 19.2, nan, 20.2, nan, nan, nan, nan, 22.3, 73.6, nan, 23.8, nan, nan, nan, 77.8, 27.8, 27.3, nan, 29.2, 29.8, nan, 31.3, 31.2, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}
age_onset : {5.3, 8.8, 9.8, 10.2, 11.0, 11.7, 12.4, 14.6, 15.6, 15.0, 17.0, 18.1, 17.9, 20.3, 21.2, 22.0, 17.2, 24.0, 21.0, 26.1, 27.0, 27.7, 26.0, 26.7, 25.7, 30.2, 25.0, 33.0, 34.1, 35.4, 30.0, 32.7, 38.6, 36.6, 41.2, 34.2, 36.2, 44.0, 45.2, 45.8, 44.7, 39.3, nan, 50.2, 51.2, 43.0, 53.4, 50.1, 46.0, 50.7, nan, 60.5, 12.0, 60.0, nan, 13.0, nan, 14.0, nan, 15.5, nan, 16.0, 16.6, 16.1, 16.5, 16.9, 17.6, 17.5, 17.1, 17.4, nan, 18.6, 18.4, 18.5, 18.0, nan, 19.6, 19.4, 19.0, 19.5, 19.1, 20.4, 20.0, 20.5, 20.6, 21.6, 21.1, 21.4, 21.5, 22.6, 22.5, 22.1, 23.9, 23.6, 24.9, 24.4, nan, 25.4, nan, 26.9, 26.4, nan, 27.9, 27.4, 28.0, 28.4, nan, 28.6, nan, 29.5, 29.9, 29.0, 30.6, 30.4, 30.1, 30.5, 31.0, nan, 32.5, 32.6, 32.0, 33.5, 33.2, 34.6, 34.0, nan, nan, 35.0, 35.7, 38.0, 13.4, nan, 39.0, 40.0, 15.4, 15.9, 42.2, nan, 44.5, nan, nan, nan, 48.7, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 13.7, nan, 14.3, nan, nan, 15.3, 15.2, 15.7, nan, nan, 16.7, 16.3, 16.8, nan, nan, 17.7, 17.3, nan, nan, 18.2, 18.8, 18.3, 18.7, nan, 19.3, nan, 19.2, 19.8, 19.7, 20.2, 20.7, nan, nan, nan, 21.8, 21.3, 21.7, nan, 22.2, 22.8, nan, 23.3, 23.2, 23.7, nan, 24.7, nan, 24.8, nan, nan, 25.3, 25.2, nan, nan, 26.2, nan, nan, 28.2, 28.7, nan, nan, 29.7, nan, nan, nan, nan, nan, nan, nan, 12.6, nan, 14.1, nan, 15.1, nan, nan, nan}
total_number_of_episodes : {0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 25.0, 27.0, nan, 34.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 1000.0, 1003.0, nan}
total_duration_of_illness_in_months : {3.2, 4.1, 5.9, 10.7, 11.8, 13.0, nan, 15.9, 19.2, 23.5, 23.0, 24.0, 28.9, 31.2, 34.0, 36.1, 37.0, nan, nan, 42.0, 45.0, nan, nan, 50.8, 51.8, nan, 56.9, nan, 58.1, 58.0, 61.0, nan, nan, 66.0, 70.0, 71.0, 72.0, 73.4, 73.9, nan, 76.5, nan, nan, 84.0, 85.3, nan, nan, nan, 94.0, 96.0, nan, nan, 103.9, 104.5, nan, 108.0, 109.8, nan, 112.9, 112.1, nan, 117.8, nan, 119.0, 120.6, 121.7, nan, nan, 126.9, 128.3, nan, 132.0, nan, 135.2, nan, 139.0, nan, 143.7, nan, 146.3, 147.0, 147.4, 149.8, 149.5, 149.0, 146.1, nan, 154.0, nan, 157.2, 158.0, nan, 161.0, 162.1, 162.5, 164.1, 162.8, 165.8, 167.4, 168.7, nan, 170.0, 171.0, nan, 173.0, 174.2, 173.7, 176.4, 174.0, 178.9, 178.2, 180.4, 181.0, 181.5, 176.9, 184.1, 185.8, 186.0, 186.8, 188.0, 189.0, 190.0, 192.0, 196.0, 197.3, 197.7, 201.0, 202.5, 201.2, 201.4, 211.4, 213.7, 214.9, 214.0, 214.5, 213.8, 215.3, 220.7, 228.0, 228.9, 232.2, 233.0, 238.0, 239.1, 240.0, 239.0, 241.4, 243.7, 238.1, 244.7, 238.8, 246.4, 247.2, 247.8, 249.0, 250.5, 243.9, 253.0, 259.0, 259.5, 261.0, 264.0, 267.3, 268.3, 268.2, 269.0, 271.5, 271.8, 273.9, 271.1, 275.5, 276.0, 276.9, 277.8, 281.0, 284.5, 287.3, 288.5, 288.6, 292.0, 293.2, 294.7, 293.0, 296.6, 296.9, 294.8, 299.9, 300.3, 301.5, 302.1, 303.8, 304.9, 301.6, 303.0, 303.7, 299.0, 311.3, 312.4, 314.8, 319.3, 322.0, 322.5, 325.5, 325.6, 327.8, 325.0, 330.9, 332.6, 333.6, 334.7, 335.2, 334.0, 337.0, 338.1, 339.0, 338.0, 337.1, 342.2, 338.9, 344.8, 345.6, 345.0, 348.4, 349.9, 350.7, 354.9, 356.0, 357.5, 358.1, 359.9, 360.6, 361.5, 361.1, 364.9, 365.4, 366.3, 371.1, 372.4, 373.6, 373.2, 375.3, 376.3, 376.1, 378.7, 378.4, 380.9, 381.9, 378.3, 384.9, 385.8, 386.5, 387.1, 389.0, 393.2, 395.6, 396.1, 397.6, 399.5, 399.9, 407.4, 411.4, 412.5, 411.6, 414.9, 416.9, 421.6, 422.2, 422.6, 427.1, 428.4, 428.2, 432.5, 433.0, 434.0, 435.4, 453.8, 456.9, 457.3, 459.0, 465.0, 466.8, nan, 470.5, 475.3, 475.5, 480.1, 485.9, nan, 490.6, 493.4, 495.0, 504.5, 507.0, nan, 512.0, 525.3, nan, 535.0, 539.9, 548.9, 552.2, 559.7, 569.9, 178.7, 181.1, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 295.6, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}
total_duration_of_all_episodes_in_months : {0.0, 1.0, 2.0, 3.5, 3.0, 4.0, 6.0, 7.0, 8.0, 9.0, 8.5, 11.0, 10.0, 13.0, 14.0, 14.5, 16.0, 15.0, 18.0, 19.0, 20.0, 21.0, 21.5, 16.5, 24.0, 25.0, 5.0, 27.0, 28.5, 5.75, 30.5, 30.0, 32.0, 33.0, 34.0, 28.0, 36.0, 7.5, 38.0, 37.0, nan, 41.5, nan, 44.0, nan, 46.0, 49.0, nan, 53.0, nan, 11.5, 2.5, nan, 61.0, 12.0, 63.5, 12.5, 63.0, 13.5, 62.0, nan, nan, nan, nan, 79.0, nan, nan, nan, 17.0, nan, nan, nan, nan, nan, 4.5, nan, 22.0, nan, 23.0, nan, nan, nan, 25.25, nan, 26.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 1000.0, 1007.0}
total_number_of_manic_episodes : {0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, nan, nan, nan, nan, 21.0, 27.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}
total_number_of_hypomanic_episodes : {0.0, 1.0, 2.0, 3.0, 4.0, nan, 6.0, 5.0, 10.0, 11.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}
total_number_of_mixed_episodes : {0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}
total_number_of_depressive_episodes : {0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, nan, nan, 13.0, 14.0, nan, 16.0, nan, nan, nan, 20.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 997.0, nan, nan, nan, nan, nan}
percentage_of_time_with_symptoms : {0.0, 1.92061459667093, 2.09832134292565, 2.29621125143513, 4.77326968973747, 5.08565310492505, 4.22498019540533, 6.4516129032258, 7.30943264879916, 9.12863070539419, 10.4903943377148, 10.0959947037404, 12.894468951476, 8.75576036866359, 11.6438356164383, 14.8876404494382, 7.93650793650793, 8.45599749451926, 18.6089078706528, 18.2149362477231, 11.5515883433972, 21.0084033613445, 22.5978647686832, 21.2765957446808, 3.22265625, 16.025641025641, 26.0416666666666, 27.6816608996539, 26.0869565217391, 28.8888888888888, 1.25, 7.5, 37.7358490566037, 37.3831775700934, 8.71677622177765, 42.3728813559322, 8.20232399179767, 46.1538461538461, 50.8474576271186, 10.4166666666666, 55.8823529411764, 12.7659574468085, 62.5, 2.90697674418604, 3.23624595469255, 16.6666666666666, 5.91397849462365, 18.9473684210526, 18.8841201716738, 97.5609756097561, 7.97984040319193, 4.43510737628384, 8.1081081081081, 2.68566090611863, 2.67558528428093, 3.51493848857645, 11.9047619047619, 3.8809831824062, 4.28571428571428, 4.4378698224852, 2.07361327112493, nan, 0.987491770901909, 0.811688311688311, 258.868894601542, 0.922168941350055, 1.23076923076923, 5.82984150118418, 6.43356643356643, 8.2135523613963, 2.98284862043251, 2.79720279720279, 9.3592512598992, 3.47912524850894, 1.30718954248366, 15.7545605306799, 4.46802569114772, 2.83745439805431, 3.22927879440258, 4.09737286093034, 410.340582683627, nan, 2.89017341040462, nan, 3.47826086956521, 11.2732095490716, 11.4754098360655, nan, 2.63204070889629, 5.44217687074829, 5.68062276456974, nan, 7.70960488274975, 2.51404909790002, 2.68199233716475, 2.57826887661141, 1.15830115830115, 1.34228187919463, 1.18028917084685, 1.22729504172803, 1.21536217792902, 1.81323662737987, 1.3531799729364, 1.61420500403551, 1.52905198776758, 1.65654334621755, 2.67062314540059, 3.15126050420168, 3.72825186412593, 4.65896384644055, 4.54545454545454, 12.4401913875598, nan, 3.87496770860242, 3.50186036331801, 16.546762589928, 6.42166836215666, 6.55105973025048, 2.61437908496732, nan, 4.03825717321997, 5.66343042071197, 8.6734693877551, 9.53678474114441, 9.77011494252873, 11.8012422360248, 13.3835215391049, nan, 15.4905335628227, nan, 4.5615813482007, nan, 5.59762923938096, nan, 2.66272189349112, nan, 0.785545954438334, nan, nan, nan, nan, 11.3636363636363, nan, 1.00984599848523, 2.31335436382754, nan, 4.44444444444444, 5.67644276253547, nan, 5.55114988104678, 6.95931477516059, nan, 2.92397660818713, nan, 3.46389555022648, nan, nan, 3.003003003003, 4.65881063305015, 4.27565392354124, nan, 4.67945718296677, 5.65291124929338, 6.0938452163315, nan, 9.78260869565217, 3.63730839179007, 3.31596399810516, 3.03030303030303, nan, 13.3828996282527, 2.46761258482418, 15.5654383735705, 3.86643233743409, 3.4987972884321, 3.44078232524447, 4.13022351797862, nan, 7.60456273764258, 1.01010101010101, nan, nan, 0.819480215406228, 1.66034155597722, 2.09142515685688, 3.7989479836353, 2.42522231204527, 2.79485746226942, 3.44530577088716, 3.57142857142857, 2.08333333333333, 2.67566309911586, 2.65151515151515, 3.15151515151515, 3.29341317365269, 2.09380234505862, nan, 1.59447249534945, nan, 7.46268656716417, 8.1190798376184, 9.822263797942, nan, 11.0671936758893, 1.76991150442477, 1.60800428801143, 2.77456647398843, nan, nan, 20.8333333333333, nan, nan, nan, nan, nan, nan, 4.2997542997543, 5.20833333333333, 5.31914893617021, 6.89021589343132, nan, 8.33333333333333, 9.9502487562189, 3.50467289719626, nan, 3.21285140562249, nan, 1.78412132024977, nan, 3.28587075575027, nan, nan, nan, nan, 1.10772639158127, 2.53592561284869, nan, 4.40976933514246, 4.78596118053709, 4.48933782267115, 7.790077900779, 8.58369098712446, 3.34728033472803, 10.3896103896103, nan, 12.637586628618, nan, 2.4793388429752, nan, nan, 4.39121756487025, 4.15973377703826, 5.54016620498614, 5.75705238917674, nan, 7.64705882352941, 1.7391304347826, nan, 4.94542974079126, 4.644681839294, 5.99078341013824, 6.52045050385299, nan, 2.17054263565891, 9.21052631578947, 3.70495116200741, nan, 11.0918544194107, nan, nan, 0.208289939595917, nan, nan, 2.31023102310231, nan, nan, nan, 5.90357494260413, 5.27704485488126, nan, 6.23538581449727, nan, 0.833487682904241, nan, nan, nan, nan, 3.42465753424657, nan, nan, nan, nan, 0.805585392051557, 0.722282412423257, 1.64642930644165, 0.750938673341677, 1.49644594089038, 1.58572844400396, 1.33779264214046, nan, nan, nan, nan, 3.15581854043392, nan, 4.2016806722689, 4.67289719626168, nan, nan, nan, nan, 7.39523418241577, nan, nan, nan, nan, nan, nan, nan, nan, nan, 3.33000333000333, 5.08905852417302, 5.27950310559006, 18.3714001986097, 6.8259385665529, 6.30417651694247, 6.89655172413793, 19.7549387346836, 7.27476217123671, 3.99274047186932, 5.77367205542725, 8.0930703085483, 10.222489476849, 3.13658397490732, 7.24881995954146, 0.870069605568445, 0.906207521522428, 3.30542089026002, 4.31177446102819, 4.24448217317487, 4.96688741721854, 7.96019900497512, 8.2063305978898, 12.6760563380281, 1.6822429906542, 14.1538461538461, 3.31491712707182, 3.26930935839803, 16.3618864292589, 4.87125956854558, 4.16782439566546, 20.2702702702702, 3.48338692390139, nan, 1.09469074986316, 3.88026607538802, 1.48323939483832, 11.8110236220472, 14.9342891278375, 15.3384461487162, 3.40136054421768, 6.32911392405063, 6.0313630880579, 7.92630676949443}
maximum_interepisodic_duration_in_months : {0.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.5, 28.0, 30.0, 31.0, 32.0, 33.0, nan, 35.0, 36.0, 34.0, 37.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 50.0, 52.0, 53.0, 54.0, 55.0, 56.0, 57.0, 58.0, 59.0, 60.0, nan, 62.5, 63.0, 67.0, 69.0, 70.0, 71.0, 72.0, 74.0, 75.0, 76.0, 77.0, 79.5, 80.0, 81.5, 79.0, 81.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 83.0, 91.0, nan, nan, 94.0, 95.0, 96.0, nan, nan, 100.0, nan, 102.0, 107.5, 108.0, 110.0, 111.0, 112.0, 115.0, 118.0, 120.0, 124.0, 126.0, 127.0, 132.0, 134.0, 135.0, 138.5, nan, 140.0, nan, 144.0, 145.5, 146.0, nan, nan, 150.0, 151.0, 156.0, nan, 166.0, 168.0, 174.0, nan, 176.0, nan, 182.0, nan, nan, 192.0, 38.0, 196.0, 197.0, 199.0, nan, 204.0, nan, 213.0, nan, 228.0, nan, nan, nan, nan, nan, 252.0, nan, nan, nan, nan, nan, 282.0, nan, nan, nan, nan, 300.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 360.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 997.0, nan, nan, nan}
rate_time_spent_euthymic_since_onset : {1.0, 2.0, 3.0, 4.0, 5.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}
rate_prominence_of_mixed_episodes : {1.0, 2.0, 3.0, 4.0, 5.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}
mania_vs_dep_first5yr : {1.0, 2.0, 3.0, 4.0, 5.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}
mania_vs_dep_recent : {1.0, 2.0, 3.0, 4.0, 5.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}
insightinterepisode : {1.0, 2.0, 3.0, 4.0, 5.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}
occupational_func_5yr : {1.0, 2.0, 3.0, 4.0, 5.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}
number_of_ip_care_recieved : {0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 997.0, nan, nan, nan, nan, nan}
a_criterion_score : {1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}
criteria_b_score : {0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 8.0, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan}

In [ ]:
for col in numerical_cols:
  df_subset[col] = df_subset[col].fillna(df_subset[col].median())